services:
  redis:
    image: redis:7-alpine
    container_name: discord-bot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - bot-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: discord-bot-qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - bot-network

volumes:
  redis_data:
    driver: local
  qdrant_data:
    driver: local

networks:
  bot-network:
    driver: bridge
